### ISSUE TITLE
The Level2 channel data not receive any data

### ISSUE THREAD

**Issue by z6yszko** [barrywood78/Coinbase.AdvancedTrade#12]
I'm trying to test WebSocketLevel2TestApp with my key. The key is valid, but socket returns no data. In the case of trades subscriptions (ChannelType.MarketTrades), the socket receive data. 
What could be the reason?

**Comment by barrywood78** [comment]
@z6yszko 

I have made many changes to the project just now.  
Specific to websockets, I have done the following:
- Added optional buffer size parameter to the CoinbaseClient (default: 5MB).
- Added WebSocketState and Subscriptions properties so you can see the current state/connection of the WebSocket.
- Modified the WebSocket Level 2 Test application to increase the buffer to 10MB as a test and it seemed to work fine.
- Added new test application to show reconnection logic.

Hope this helps resolve your issue!

Barry

**Comment by z6yszko** [comment]
Great job! Thank you!
