### ISSUE TITLE
Native .NET Fwk librairies

### ISSUE THREAD

**Issue by M0aB0z** [barrywood78/Coinbase.AdvancedTrade#21]
Hi,

Thanks for your amazing job on this library, very appreciate it.

I'd like to propose some improvements:

- Use native HttpClient instead of RestSharp
- Use System.Text.Json native library instead of newtonsoft
- Convert strings properties to numerics when it refers to pricing values
- Use cancellation tokens on async calls

I can do this rework through a pull request if you're ok, otherwise I'll forked your client.

Thanks again for this quality job.

**Comment by barrywood78** [comment]
Hi, thanks for the suggestion.  I've been meaning to put together a new version of this to include Coinbase's latest API changes but have been busy with other projects.  I will look at dropping RestSharp and a few other suggestions but some things will remain as I have a requirement for the library to with the older .NET Framework which means .NET Standard 2.0.  I see you forked it anyways so you're on your way.  

Thanks!
